#Logistic Regression Model

In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as pltbm
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import pickle

In [14]:
X_train = pd.read_csv("/content/drive/MyDrive/Collab/Beginner Classification/X_train.csv")
Y_train = pd.read_csv("/content/drive/MyDrive/Collab/Beginner Classification/Y_train.csv")
X_test = pd.read_csv("/content/drive/MyDrive/Collab/Beginner Classification/X_test.csv")
Y_test = pd.read_csv("/content/drive/MyDrive/Collab/Beginner Classification/Y_test.csv")

In [15]:
model = LogisticRegression()

In [16]:
model.fit(X_train,Y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [17]:
predict_train = model.predict(X_train)
predict_train

array([0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0.,
       1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1.,
       0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1.,
       1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0.,
       1., 0., 1., 0., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 1.,
       0., 1., 0., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1.,
       0., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1.,
       1., 0., 1., 0., 1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 1., 1.,
       1., 0., 0., 1., 0., 1., 1., 1., 0., 1., 1., 0., 0., 1., 0., 0., 1.,
       1., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 1., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1., 1.,
       1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 1., 0., 1.,
       1., 1., 1., 1., 1.

In [18]:
predict_test = model.predict(X_test)
predict_test

array([0., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0.,
       0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
       0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 0., 1., 1., 0.])

In [19]:
accuracy_test

0.95

# Saving the model

In [25]:
filename = '/content/drive/MyDrive/Model/Logistic_Regression.pkl'
pickle.dump(model, open(filename, 'wb'))

In [26]:
model = pickle.load(open(filename, 'rb'))
model.predict(X_test)

array([0., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0.,
       0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
       0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 0., 1., 1., 0.])